In [1]:
import numpy as np
import os

In [3]:
import torch


In [4]:
data = torch.zeros([210,12])

In [5]:
values = open('data.txt',"r")
i=0
for line in values:
    
    j=0
    splitted_line = line.split(' ')
    splitted_line = splitted_line[:-1]
    
    for numbers in splitted_line:
        number = int(numbers)
        data[i,j] = number
        j+=1
    i+=1

In [6]:
data

tensor([[   3.,    9.,   12.,  ...,  369.,  597.,  966.],
        [   3.,   13.,   16.,  ...,  505.,  817., 1322.],
        [   3.,   17.,   20.,  ...,  641., 1037., 1678.],
        ...,
        [  54.,   55.,  109.,  ..., 3004., 4861., 7865.],
        [  54.,   60.,  114.,  ..., 3174., 5136., 8310.],
        [  55.,   60.,  115.,  ..., 3195., 5170., 8365.]])

In [7]:
data.dtype

torch.float32

In [8]:
import torch.nn as nn
import torch.nn.functional as F

In [109]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = nn.Linear(5,1, bias=False)
        
    def forward(self,x):
        x = (self.fc1(x))
        return x
    
    
model = Model()    

In [110]:
import torch.optim as optim

In [111]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [114]:
for epoch in range(30):
    running_loss = 0.0
    
    for j in range(10):
        a = torch.zeros((210,5))
        q = 1
        k=j
        while k+2>0 and q<6:
            a[:,-q] = data[:,k+1]
            k-=1
            q+=1

        optimizer.zero_grad()
        output = model(a)
        out = torch.zeros((210,1))
        out[:,0] = data[:,j+2]


        loss = criterion(output, out)
        loss.backward()
        torch.nn.utils.clip_grad_norm(model.parameters(),5.0)
        optimizer.step()
        print(a)
        print(out)
        print(output)
        
        running_loss += loss
        if j==9:
            print(' %.3f' %( running_loss))
            running_loss = 0.0
            
print((abs((output-out)/out)*100).mean())            
print('finished training')                
                

C:\Users\Akshit Mittal\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.


tensor([[ 0.,  0.,  0.,  3.,  9.],
        [ 0.,  0.,  0.,  3., 13.],
        [ 0.,  0.,  0.,  3., 17.],
        ...,
        [ 0.,  0.,  0., 54., 55.],
        [ 0.,  0.,  0., 54., 60.],
        [ 0.,  0.,  0., 55., 60.]])
tensor([[ 12.],
        [ 16.],
        [ 20.],
        [ 25.],
        [ 29.],
        [ 31.],
        [ 32.],
        [ 34.],
        [ 36.],
        [ 40.],
        [ 42.],
        [ 44.],
        [ 45.],
        [ 47.],
        [ 49.],
        [ 52.],
        [ 54.],
        [ 57.],
        [ 58.],
        [ 63.],
        [ 22.],
        [ 26.],
        [ 31.],
        [ 35.],
        [ 37.],
        [ 38.],
        [ 40.],
        [ 42.],
        [ 46.],
        [ 48.],
        [ 50.],
        [ 51.],
        [ 53.],
        [ 55.],
        [ 58.],
        [ 60.],
        [ 63.],
        [ 64.],
        [ 69.],
        [ 30.],
        [ 35.],
        [ 39.],
        [ 41.],
        [ 42.],
        [ 44.],
        [ 46.],
        [ 50.],
        [ 52.],
        

        [755.]])
tensor([[ 88.2013],
        [120.6953],
        [153.1894],
        [193.8069],
        [226.3009],
        [242.5479],
        [250.6714],
        [266.9184],
        [283.1654],
        [315.6595],
        [331.9065],
        [348.1535],
        [356.2770],
        [372.5240],
        [388.7710],
        [413.1415],
        [429.3885],
        [453.7590],
        [461.8826],
        [502.5001],
        [150.8749],
        [183.3689],
        [223.9865],
        [256.4805],
        [272.7275],
        [280.8510],
        [297.0980],
        [313.3450],
        [345.8390],
        [362.0860],
        [378.3330],
        [386.4565],
        [402.7036],
        [418.9506],
        [443.3211],
        [459.5681],
        [483.9386],
        [492.0621],
        [532.6796],
        [203.4886],
        [244.1061],
        [276.6002],
        [292.8472],
        [300.9707],
        [317.2177],
        [333.4647],
        [365.9587],
        [382.2057],
        [398.4528],
   

tensor([[  21.,   33.,   54.,   87.,  141.],
        [  29.,   45.,   74.,  119.,  193.],
        [  37.,   57.,   94.,  151.,  245.],
        ...,
        [ 164.,  273.,  437.,  710., 1147.],
        [ 174.,  288.,  462.,  750., 1212.],
        [ 175.,  290.,  465.,  755., 1220.]])
tensor([[ 228.],
        [ 312.],
        [ 396.],
        [ 501.],
        [ 585.],
        [ 627.],
        [ 648.],
        [ 690.],
        [ 732.],
        [ 816.],
        [ 858.],
        [ 900.],
        [ 921.],
        [ 963.],
        [1005.],
        [1068.],
        [1110.],
        [1173.],
        [1194.],
        [1299.],
        [ 390.],
        [ 474.],
        [ 579.],
        [ 663.],
        [ 705.],
        [ 726.],
        [ 768.],
        [ 810.],
        [ 894.],
        [ 936.],
        [ 978.],
        [ 999.],
        [1041.],
        [1083.],
        [1146.],
        [1188.],
        [1251.],
        [1272.],
        [1377.],
        [ 526.],
        [ 631.],
        [ 715.],
  

tensor([[  54.,   87.,  141.,  228.,  369.],
        [  74.,  119.,  193.,  312.,  505.],
        [  94.,  151.,  245.,  396.,  641.],
        ...,
        [ 437.,  710., 1147., 1857., 3004.],
        [ 462.,  750., 1212., 1962., 3174.],
        [ 465.,  755., 1220., 1975., 3195.]])
tensor([[ 597.],
        [ 817.],
        [1037.],
        [1312.],
        [1532.],
        [1642.],
        [1697.],
        [1807.],
        [1917.],
        [2137.],
        [2247.],
        [2357.],
        [2412.],
        [2522.],
        [2632.],
        [2797.],
        [2907.],
        [3072.],
        [3127.],
        [3402.],
        [1021.],
        [1241.],
        [1516.],
        [1736.],
        [1846.],
        [1901.],
        [2011.],
        [2121.],
        [2341.],
        [2451.],
        [2561.],
        [2616.],
        [2726.],
        [2836.],
        [3001.],
        [3111.],
        [3276.],
        [3331.],
        [3606.],
        [1377.],
        [1652.],
        [1872.],
  

tensor([[ 966.],
        [1322.],
        [1678.],
        [2123.],
        [2479.],
        [2657.],
        [2746.],
        [2924.],
        [3102.],
        [3458.],
        [3636.],
        [3814.],
        [3903.],
        [4081.],
        [4259.],
        [4526.],
        [4704.],
        [4971.],
        [5060.],
        [5505.],
        [1652.],
        [2008.],
        [2453.],
        [2809.],
        [2987.],
        [3076.],
        [3254.],
        [3432.],
        [3788.],
        [3966.],
        [4144.],
        [4233.],
        [4411.],
        [4589.],
        [4856.],
        [5034.],
        [5301.],
        [5390.],
        [5835.],
        [2228.],
        [2673.],
        [3029.],
        [3207.],
        [3296.],
        [3474.],
        [3652.],
        [4008.],
        [4186.],
        [4364.],
        [4453.],
        [4631.],
        [4809.],
        [5076.],
        [5254.],
        [5521.],
        [5610.],
        [6055.],
        [2893.],
        [3249.

tensor([[ 937.7425],
        [1283.3258],
        [1628.9092],
        [2060.8882],
        [2406.4717],
        [2579.2634],
        [2665.6592],
        [2838.4507],
        [3011.2427],
        [3356.8262],
        [3529.6177],
        [3702.4092],
        [3788.8052],
        [3961.5969],
        [4134.3882],
        [4393.5762],
        [4566.3677],
        [4825.5552],
        [4911.9512],
        [5343.9307],
        [1603.6858],
        [1949.2690],
        [2381.2480],
        [2726.8315],
        [2899.6230],
        [2986.0190],
        [3158.8108],
        [3331.6025],
        [3677.1860],
        [3849.9775],
        [4022.7690],
        [4109.1650],
        [4281.9565],
        [4454.7480],
        [4713.9360],
        [4886.7275],
        [5145.9150],
        [5232.3110],
        [5664.2900],
        [2162.8423],
        [2594.8213],
        [2940.4048],
        [3113.1965],
        [3199.5923],
        [3372.3840],
        [3545.1758],
        [3890.7590],
        [4063

tensor([[ 988.9840],
        [1353.4519],
        [1717.9196],
        [2173.5042],
        [2537.9719],
        [2720.2058],
        [2811.3228],
        [2993.5566],
        [3175.7905],
        [3540.2583],
        [3722.4919],
        [3904.7261],
        [3995.8428],
        [4178.0767],
        [4360.3105],
        [4633.6611],
        [4815.8955],
        [5089.2461],
        [5180.3633],
        [5635.9478],
        [1691.3149],
        [2055.7830],
        [2511.3674],
        [2875.8350],
        [3058.0691],
        [3149.1860],
        [3331.4199],
        [3513.6538],
        [3878.1216],
        [4060.3555],
        [4242.5894],
        [4333.7061],
        [4515.9399],
        [4698.1738],
        [4971.5244],
        [5153.7588],
        [5427.1094],
        [5518.2266],
        [5973.8105],
        [2281.0249],
        [2736.6096],
        [3101.0771],
        [3283.3115],
        [3374.4282],
        [3556.6621],
        [3738.8960],
        [4103.3633],
        [4285

tensor([[  0.,   0.,   3.,   9.,  12.],
        [  0.,   0.,   3.,  13.,  16.],
        [  0.,   0.,   3.,  17.,  20.],
        ...,
        [  0.,   0.,  54.,  55., 109.],
        [  0.,   0.,  54.,  60., 114.],
        [  0.,   0.,  55.,  60., 115.]])
tensor([[ 21.],
        [ 29.],
        [ 37.],
        [ 47.],
        [ 55.],
        [ 59.],
        [ 61.],
        [ 65.],
        [ 69.],
        [ 77.],
        [ 81.],
        [ 85.],
        [ 87.],
        [ 91.],
        [ 95.],
        [101.],
        [105.],
        [111.],
        [113.],
        [123.],
        [ 35.],
        [ 43.],
        [ 53.],
        [ 61.],
        [ 65.],
        [ 67.],
        [ 71.],
        [ 75.],
        [ 83.],
        [ 87.],
        [ 91.],
        [ 93.],
        [ 97.],
        [101.],
        [107.],
        [111.],
        [117.],
        [119.],
        [129.],
        [ 47.],
        [ 57.],
        [ 65.],
        [ 69.],
        [ 71.],
        [ 75.],
        [ 79.],
        [ 

tensor([[ 54.5341],
        [ 74.7635],
        [ 94.9929],
        [120.2796],
        [140.5089],
        [150.6236],
        [155.6810],
        [165.7956],
        [175.9103],
        [196.1397],
        [206.2544],
        [216.3690],
        [221.4264],
        [231.5411],
        [241.6558],
        [256.8278],
        [266.9425],
        [282.1145],
        [287.1718],
        [312.4586],
        [ 92.7996],
        [113.0289],
        [138.3156],
        [158.5450],
        [168.6597],
        [173.7170],
        [183.8317],
        [193.9464],
        [214.1758],
        [224.2905],
        [234.4051],
        [239.4625],
        [249.5771],
        [259.6918],
        [274.8639],
        [284.9785],
        [300.1506],
        [305.2079],
        [330.4946],
        [125.0530],
        [150.3397],
        [170.5691],
        [180.6837],
        [185.7411],
        [195.8558],
        [205.9705],
        [226.1998],
        [236.3145],
        [246.4292],
        [251.4865],


tensor([[ 52.2594],
        [ 71.6692],
        [ 91.0790],
        [115.3412],
        [134.7510],
        [144.4559],
        [149.3083],
        [159.0132],
        [168.7181],
        [188.1279],
        [197.8328],
        [207.5377],
        [212.3901],
        [222.0950],
        [231.7999],
        [246.3573],
        [256.0621],
        [270.6195],
        [275.4719],
        [299.7342],
        [ 88.8440],
        [108.2538],
        [132.5160],
        [151.9258],
        [161.6307],
        [166.4831],
        [176.1880],
        [185.8929],
        [205.3027],
        [215.0076],
        [224.7125],
        [229.5649],
        [239.2698],
        [248.9747],
        [263.5320],
        [273.2369],
        [287.7943],
        [292.6467],
        [316.9089],
        [119.7036],
        [143.9659],
        [163.3756],
        [173.0805],
        [177.9330],
        [187.6379],
        [197.3427],
        [216.7525],
        [226.4574],
        [236.1623],
        [241.0148],


In [1]:
torch.save(model.state_dict(), 'model.pt')

NameError: name 'torch' is not defined

In [127]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-0.0058, -0.0215, -0.0919,  1.0238,  1.0382]]))])

In [108]:
for param in model.parameters():
  print(param.data)

tensor([[ 0.0985,  0.0645, -0.0541,  1.0051,  1.0433]])
tensor([0.3846])
